config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :books
  resources :posts
  resources :comments, only: [:create, :destroy]
  devise_for :users
  resources :users do
    member do
      get :friends
      get :followers
      get :deactivate
    end
  end
  resources :events, except: [:edit, :update]

  resources :favorite_books

  get 'favorite_books/show/:user' => 'favorite_books#show', :as => :show_favorite_books
  delete '/favorite_books/:book_id' => 'favorite_books#destroy', :as => :delete_favorite_book

  resources :authors
  resources :genres
  
  authenticated :user do
    root to: 'home#index', as: 'home'
  end
  unauthenticated :user do
    root 'home#front'
  end

  match 'books/add_new_comment' => 'books#add_new_comment', :as => "add_new_comment_to_books", :via => [:post]

  match :follow, to: 'follows#create', as: :follow, via: :post
  match :unfollow, to: 'follows#destroy', as: :unfollow, via: :post
  match :like, to: 'likes#create', as: :like, via: :post
  match :unlike, to: 'likes#destroy', as: :unlike, via: :post
  match :find_friends, to: 'home#find_friends', as: :find_friends, via: :get
  match :about, to: 'home#about', as: :about, via: :get

end

app/models/favorite_book.rb
class FavoriteBook < ActiveRecord::Base

  #validates :user_id, :book_id, limit: {must_equal:1}
  #validates :book_id
  # validates :user_id, :uniqueness => {:scope => :book_id , :message => "Only add on book to your favorites"}
end

app/controllers/favorite_books_controller.rb
class FavoriteBooksController < ApplicationController

  layout 'application'

  def create
    favorite_book = FavoriteBook.find_by user_id: params[:user_id], book_id: params[:book_id]
    if favorite_book.nil?
      favorite_book = FavoriteBook.create(user_id: params[:user_id], book_id: params[:book_id])
      if favorite_book
        flash[:notice] = "#{params[:book_name]} has been successfully added to your favorites list."
        redirect_to :back
      else
        flash[:alert] = "Error adding #{params[:book_name]} to your favorites list."
        redirect_to :back
      end
    else
      flash[:alert] = "#{params[:book_name]} is already in your favorites list."
      redirect_to :back
    end    
  end

  def destroy
    book = Book.find(params[:id])
    favorite_book = FavoriteBook.find_by user_id: params[:user_id], book_id: params[:id]
    favorite_book.destroy
    flash[:notice] = "#{book} has been successfully deleted from your favorites' list."
    redirect_to :back
  end

  def show
    @user = User.find(params[:user])
    @favorite_books = []
    @favorite_books_ids = FavoriteBook.where(user_id: @user.id)

    @favorite_books_ids.each do |faves|
      @favorite_books.push(Book.find(faves.book_id))
    end
  end



end

app/views/favorite_books/show.html.erb
<h1><%= "#{@user.name}'s Favorite Books" %></h1><br />

<table>
  <tr>
    <th></th>
    <th>TITLE</th>
    <th>AUTHOR</th>
    <th>GENRE</th>
    <th></th>
  </tr>
  <% if is_current_user?(@user) %>
    <% @favorite_books.each do |book| %>
      <tr>
        <td class="book_img"><%= image_tag("books/#{book.image_name}.jpg", alt: 'Example', class: "book_cover") %></td>
          <td><%= link_to book.name, book_path(book) %></td>
          <td><%= book.author %></td>
          <td><%= book.genre %></td>
          <td><%= link_to "Delete from favorites", delete_favorite_book_path(book, :user_id => @user.id), :method => :delete, :confirm => "Are you sure?" %></td>
      </tr>
    <% end %>
  <% else %>
    <% @favorite_books.each do |book| %>
      <tr>
        <td class="book_img"><%= image_tag("books/#{book.image_name}.jpg", alt: 'Example', class: "book_cover") %></td>
          <td><%= link_to book.name, book_path(book) %></td>
          <td><%= book.author %></td>
          <td><%= book.genre %></td>
          <td><%= link_to "Add to favorites", favorite_books_path(:book_id => book.id, :user_id => current_user.id, :book_name => book.name), :action => :create, :method => :post %></td>
      </tr>
    <% end %>
  <% end %>
</table>


<br />